behaviors:
  LocalCameraBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    behavioral_cloning:
      demo_path: ThreePointTurn/ThreePointTurn.demo
      strength: 0.5
      steps: 150000
      batch_size: 512
      num_epoch: 3
      samples_per_update: 0
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        gamma: 0.99
        encoding_size: 128
        demo_path: ThreePointTurn/ThreePointTurn.demo
        learning_rate: 3.0e-4
        use_actions: false
        use_vail: false
    keep_checkpoints: 5
    max_steps: 10000000000
    time_horizon: 64
    summary_freq: 5000
    
  LocalRNNCameraBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 5
      vis_encode_type: simple
      memory:
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    behavioral_cloning:
      demo_path: Demos/WaypointsRay2.demo
      strength: 0.5
      steps: 150000
      batch_size: 512
      num_epoch: 3
      samples_per_update: 0
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        gamma: 0.99
        encoding_size: 128
        demo_path: Demos/WaypointsRay2.demo
        learning_rate: 3.0e-4
        use_actions: false
        use_vail: false
    keep_checkpoints: 5
    max_steps: 10000000000
    time_horizon: 64
    summary_freq: 5000
  ThreeLayerLocalCameraBrain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    behavioral_cloning:
      demo_path: Demos/WaypointsRay2.demo
      strength: 0.5
      steps: 150000
      batch_size: 512
      num_epoch: 3
      samples_per_update: 0
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        gamma: 0.99
        encoding_size: 128
        demo_path: Demos/WaypointsRay2.demo
        learning_rate: 3.0e-4
        use_actions: false
        use_vail: false
    keep_checkpoints: 5
    max_steps: 10000000000
    time_horizon: 64
    summary_freq: 5000